image: Visual Studio 2019
skip_branch_with_pr: true
configuration: Release
install:
  - choco install gitversion.portable --pre -y
#  - choco install gitversion.portable -y --version=4.0.0
  - gitversion /l console /output buildserver
  - choco install opencover.portable -y
  - choco install codecov -y
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml, codecov.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml, codecov.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{GitVersion_SemVer}'
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemFileVer)
  informational_version: $(GitVersion_InformationalVersion)
nuget:
  project_feed: true
#  disable_publish_on_pr: true
before_build:
  - dotnet restore
build:
  project: IbanNet.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
test_script:
  - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test -c Release /p:DebugType=full -l:trx;LogFilePrefix=testresults" -output:coverage.xml -register:user -returntargetcode -filter:"+[IbanNet*]* -[*Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverageAttribute;*.GeneratedCodeAttribute;*.DebuggerNonUserCodeAttribute;*.CompilerGeneratedAttribute;*.DebuggerHiddenAttribute -oldStyle
  - codecov -f coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: t2/l0pnxGqkmSAUF/246qpdeu0BcGYZbcrTvgyKD8ksY5oSFyrya+mkl7E26h5iP
  on:
    branch:
    - master
    - /release\/.+/
