image: Visual Studio 2022
skip_branch_with_pr: true
configuration: Release
environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  CLI_VERSION: 7.0.101
install:
  - choco install gitversion.portable -y
  - gitversion /l console /output buildserver
  - choco install opencover.portable -y
  - choco install codecov -y
  # Install 7.0.101 until AppVeyor updates their image
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml, codecov.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml, codecov.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{GitVersion_SemVer}'
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemFileVer)
  informational_version: $(GitVersion_InformationalVersion)
nuget:
  project_feed: true
#  disable_publish_on_pr: true
before_build:
  - dotnet restore
build:
  project: IbanNet.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
test_script:
  - OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test -c Release /p:DebugType=full -l:trx;LogFilePrefix=testresults" -output:coverage.xml -register:user -returntargetcode -filter:"+[IbanNet*]* -[*Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverageAttribute;*.GeneratedCodeAttribute;*.DebuggerNonUserCodeAttribute;*.CompilerGeneratedAttribute;*.DebuggerHiddenAttribute -oldStyle
  - codecov -f coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: LYK2kBW5UKfW19u4OR0m91tWA4/+kvmPQKm721Gp/VPjKU6F0pO4E8XrhId71pVp
  on:
    APPVEYOR_REPO_TAG: true
